server:
  port: 2000
  context-path: /doclet-api
  tomcat:
    basedir: ${user.home}/tomcatTemp
spring:
  datasource:
    url: jdbc:h2:file:~/.h2/javaDoc
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org.hibernate: DEBUG